source 'https://cdn.cocoapods.org/'

target 'ApplePlatformsIntegrationMobileTests' do
  use_frameworks!
  platform :ios, '12.0'
  pod 'hermes-engine', :path => '../../'
end

target 'ApplePlatformsIntegrationTVOSTests' do
  use_frameworks!
  platform :tvos, '15.0'
  pod 'hermes-engine', :path => '../../'
end

target 'ApplePlatformsIntegrationMacTests' do
  use_frameworks!
  platform :osx, '10.14'
  pod 'hermes-engine', :path => '../../'
end
